In [1]:
! pip install vllm

Collecting vllm
  Downloading vllm-0.28.0-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from vllm) (2025.11.3)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (6.2.6)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from vllm) (5.9.5)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from vllm) (0.2.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from vllm) (2.0.2)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from vllm) (4.67.3)
Requirement already satisfied: blake3 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.0.9)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)
Collecting transformers>=5.5.3 (from vllm)
  Downloading transformers-5.16.1-py3-none-any.whl.metadata (32 kB)
Collecting huggingface_hub>=1.27.0 (from vllm)
  Downloading huggingface_hub-1.30.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.22.2)
Requirement already satisfied: safetensors>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.7.0)
Collecting protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 (from vllm)
  Downloading protobuf-7.36.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: fastapi<0.137.0,>=0.133.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]<0.137.0,>=0.133.0->vllm) (0.136.1)
Collecting starlette>=1.0.1 (from vllm)
  Downloading starlette-1.6.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.13.5)
Requirement already satisfied: openai>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.0)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.12.3)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.25.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm) (11.3.0)
Collecting prometheus-fastapi-instrumentator>=8.0.0 (from vllm)
  Downloading prometheus_fastapi_instrumentator-8.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.12.0)
Collecting lm-format-enforcer==0.11.3 (from vllm)
  Downloading lm_format_enforcer-0.11.3-py3-none-any.whl.metadata (17 kB)
Collecting llguidance<1.8.0,>=1.7.0 (from vllm)
  Downloading llguidance-1.7.6-cp39-abi3-manylinux_2_31_x86_64.whl.metadata (10 kB)
Collecting outlines_core==0.2.14 (from vllm)
  Downloading outlines_core-0.2.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)
Collecting lark==1.2.2 (from vllm)
  Downloading lark-1.2.2-py3-none-any.whl.metadata (1.8 kB)
Collecting xgrammar<1.0.0,>=0.2.1 (from vllm)
  Downloading xgrammar-0.2.5.post1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.5 kB)
Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.15.0)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.29.0)
Collecting partial-json-parser (from vllm)
  Downloading partial_json_parser-0.2.1.1.post7-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: jsonschema>=4.23.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.26.0)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)
Collecting msgspec (from vllm)
  Downloading msgspec-0.21.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Collecting mistral_common>=1.11.6 (from mistral_common[image]>=1.11.6->vllm)
  Downloading mistral_common-1.11.7-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: opencv-python-headless>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.13.0.92)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from vllm) (6.0.3)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)
Collecting setuptools<81.0.0,>=77.0.3 (from vllm)
  Downloading setuptools-80.10.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.2)
Collecting compressed-tensors==0.17.0 (from vllm)
  Downloading compressed_tensors-0.17.0-py3-none-any.whl.metadata (4.7 kB)
Collecting depyf==0.20.0 (from vllm)
  Downloading depyf-0.20.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.2)
Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from vllm) (1.1.1)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.1.0)
Requirement already satisfied: ninja in /usr/local/lib/python3.12/dist-packages (from vllm) (1.13.0)
Collecting pybase64 (from vllm)
  Downloading pybase64-1.5.0-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (11 kB)
Collecting cbor2 (from vllm)
  Downloading cbor2-6.1.4-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting ijson (from vllm)
  Downloading ijson-3.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting setproctitle (from vllm)
  Downloading setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (10 kB)
Collecting openai-harmony>=0.0.3 (from vllm)
  Downloading openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Collecting anthropic>=0.71.0 (from vllm)
  Downloading anthropic-1.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting model-hosting-container-standards<1.0.0,>=0.1.14 (from vllm)
  Downloading model_hosting_container_standards-0.1.16-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: mcp in /usr/local/lib/python3.12/dist-packages (from vllm) (1.27.0)
Requirement already satisfied: opentelemetry-sdk>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.38.0)
Requirement already satisfied: opentelemetry-api>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.38.0)
Collecting opentelemetry-exporter-otlp>=1.27.0 (from vllm)
  Downloading opentelemetry_exporter_otlp-1.44.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-semantic-conventions-ai>=0.4.1 (from vllm)
  Downloading opentelemetry_semantic_conventions_ai-0.5.1-py3-none-any.whl.metadata (997 bytes)
Collecting numba==0.65.0 (from vllm)
  Downloading numba-0.65.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting torch==2.13.0 (from vllm)
  Downloading torch-2.13.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (38 kB)
Collecting torchaudio==2.11.0 (from vllm)
  Downloading torchaudio-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting torchvision==0.28.0 (from vllm)
  Downloading torchvision-0.28.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Collecting torchcodec>=0.14 (from vllm)
  Downloading torchcodec-0.16.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.7 kB)
Collecting PyNvVideoCodec==2.0.4 (from vllm)
  Downloading pynvvideocodec-2.0.4-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting flashinfer-python==0.6.16.post3 (from vllm)
  Downloading flashinfer_python-0.6.16.post3-py3-none-any.whl.metadata (11 kB)
Collecting apache-tvm-ffi==0.1.11 (from vllm)
  Downloading apache_tvm_ffi-0.1.11-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting tilelang==0.1.12 (from vllm)
  Downloading tilelang-0.1.12-cp38-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (15 kB)
Collecting nvidia-cudnn-frontend>=1.19.1 (from vllm)
  Downloading nvidia_cudnn_frontend-1.28.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (17 kB)
Requirement already satisfied: nvtx==0.2.15 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.2.15)
Collecting fastsafetensors>=0.3.3 (from vllm)
  Downloading fastsafetensors-0.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting nvidia-cutlass-dsl==4.6.2 (from nvidia-cutlass-dsl[cu13]==4.6.2->vllm)
  Downloading nvidia_cutlass_dsl-4.6.2-py3-none-any.whl.metadata (2.8 kB)
Collecting quack-kernels==0.6.4 (from vllm)
  Downloading quack_kernels-0.6.4-py3-none-any.whl.metadata (838 bytes)
Collecting tokenspeed-mla==0.1.8 (from vllm)
  Downloading tokenspeed_mla-0.1.8-py3-none-manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting humming-kernels==0.1.12 (from humming-kernels[cu13]==0.1.12->vllm)
  Downloading humming_kernels-0.1.12-py3-none-manylinux_2_28_x86_64.whl.metadata (4.0 kB)
Collecting loguru (from compressed-tensors==0.17.0->vllm)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Collecting astor (from depyf==0.20.0->vllm)
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.4.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (8.3.3)
Requirement already satisfied: cuda-python>=12.0 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (12.9.4)
Collecting cuda-tile>=1.4.0 (from flashinfer-python==0.6.16.post3->vllm)
  Downloading cuda_tile-1.5.0-cp312-cp312-manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting nccl4py>=0.3.1 (from flashinfer-python==0.6.16.post3->vllm)
  Downloading nccl4py-0.5.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (13.595.45)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (26.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.16.post3->vllm) (0.9.0)
Requirement already satisfied: triton in /usr/local/lib/python3.12/dist-packages (from humming-kernels==0.1.12->humming-kernels[cu13]==0.1.12->vllm) (3.6.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from humming-kernels==0.1.12->humming-kernels[cu13]==0.1.12->vllm) (3.1.6)
Requirement already satisfied: cuda-bindings in /usr/local/lib/python3.12/dist-packages (from humming-kernels==0.1.12->humming-kernels[cu13]==0.1.12->vllm) (12.9.4)
Collecting nvidia-cuda-runtime (from humming-kernels[cu13]==0.1.12->vllm)
  Downloading nvidia_cuda_runtime-13.3.29-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-cccl (from humming-kernels[cu13]==0.1.12->vllm)
  Downloading nvidia_cuda_cccl-13.3.3.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvcc (from humming-kernels[cu13]==0.1.12->vllm)
  Downloading nvidia_cuda_nvcc-13.3.73-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cuda-nvrtc (from humming-kernels[cu13]==0.1.12->vllm)
  Downloading nvidia_cuda_nvrtc-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)
Collecting interegular>=0.3.2 (from lm-format-enforcer==0.11.3->vllm)
  Downloading interegular-0.3.3-py37-none-any.whl.metadata (3.0 kB)
Collecting llvmlite<0.48,>=0.47.0dev0 (from numba==0.65.0->vllm)
  Downloading llvmlite-0.47.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Collecting nvidia-cutlass-dsl-libs-base==4.6.2 (from nvidia-cutlass-dsl==4.6.2->nvidia-cutlass-dsl[cu13]==4.6.2->vllm)
  Downloading nvidia_cutlass_dsl_libs_base-4.6.2-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (2.8 kB)
Collecting nvidia-cutlass-dsl-libs-cu12==4.6.2 (from nvidia-cutlass-dsl==4.6.2->nvidia-cutlass-dsl[cu13]==4.6.2->vllm)
  Downloading nvidia_cutlass_dsl_libs_cu12-4.6.2-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (2.8 kB)
Collecting nvidia-cutlass-dsl-libs-cu13==4.6.2 (from nvidia-cutlass-dsl[cu13]==4.6.2->vllm)
  Downloading nvidia_cutlass_dsl_libs_cu13-4.6.2-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (2.8 kB)
Collecting torch-c-dlpack-ext (from quack-kernels==0.6.4->vllm)
  Downloading torch_c_dlpack_ext-0.1.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from tilelang==0.1.12->vllm) (0.5.4)
Collecting z3-solver<4.15.5,>=4.13.0 (from tilelang==0.1.12->vllm)
  Downloading z3_solver-4.15.4.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (602 bytes)
Collecting tokenspeed-triton>=3.7.10.post20260531 (from tokenspeed-mla==0.1.8->vllm)
  Downloading tokenspeed_triton-3.8.10.post20260721-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.0 kB)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->vllm) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->vllm) (3.6.1)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.13.0->vllm) (2025.3.0)
Collecting cuda-toolkit==13.0.3 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading cuda_toolkit-13.0.3.0-py2.py3-none-any.whl.metadata (17 kB)
Collecting cuda-bindings (from humming-kernels==0.1.12->humming-kernels[cu13]==0.1.12->vllm)
  Downloading cuda_bindings-13.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting nvidia-cudnn-cu13==9.20.0.48 (from torch==2.13.0->vllm)
  Downloading nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from torch==2.13.0->vllm)
  Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.29.7 (from torch==2.13.0->vllm)
  Downloading nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch==2.13.0->vllm)
  Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton (from humming-kernels==0.1.12->humming-kernels[cu13]==0.1.12->vllm)
  Downloading triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cublas==13.1.1.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-nvrtc (from humming-kernels[cu13]==0.1.12->vllm)
  Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime (from humming-kernels[cu13]==0.1.12->vllm)
  Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink<14,>=13.0.88 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch==2.13.0->vllm)
  Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 (from vllm)
  Downloading protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting nvidia-cuda-nvdisasm<14,>=13.3 (from nvidia-cutlass-dsl-libs-base==4.6.2->nvidia-cutlass-dsl==4.6.2->nvidia-cutlass-dsl[cu13]==4.6.2->vllm)
  Downloading nvidia_cuda_nvdisasm-13.3.73-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cutlass-dsl-libs-core==4.6.2 (from nvidia-cutlass-dsl-libs-base==4.6.2->nvidia-cutlass-dsl==4.6.2->nvidia-cutlass-dsl[cu13]==4.6.2->vllm)
  Downloading nvidia_cutlass_dsl_libs_core-4.6.2-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (0.4.1)

In [2]:
from vllm import LLM, SamplingParams
LLM_MODEL = 'Qwen/Qwen3-4B-Instruct-2507'
llm = LLM(model=LLM_MODEL,dtype="float16",tensor_parallel_size=2,max_model_len=1024,gpu_memory_utilization=0.90)

INFO 09-06 19:33:41 [api_utils.py:272] non-default args: {'dtype': 'float16', 'max_model_len': 1024, 'tensor_parallel_size': 2, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'Qwen/Qwen3-4B-Instruct-2507'}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

INFO 09-06 19:33:57 [model.py:672] Resolved architecture: Qwen3ForCausalLM
WARNING 09-06 19:33:57 [model.py:2299] Casting torch.bfloat16 to torch.float16.
INFO 09-06 19:33:57 [model.py:1965] Using max model len 1024
INFO 09-06 19:33:57 [scheduler.py:242] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-06 19:33:57 [kernel.py:308] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

tokenizer_config.json:   0%|          | 0.00/9.38k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

generation_config.json:   0%|          | 0.00/238 [00:00<?, ?B/s]

(EngineCore pid=201) INFO 09-06 19:34:01 [core.py:122] Initializing a V1 LLM engine (v0.28.0) with config: model='Qwen/Qwen3-4B-Instruct-2507', speculative_config=None, tokenizer='Qwen/Qwen3-4B-Instruct-2507', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=Qwen/Qwen3-4B-Instruct-2507, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')
(EngineCore pid=201) INFO 09-06 19:34:01 [multiproc_executor.py:150] DP group leader: node_rank=0, node_rank_within_dp=0, master_addr=127.0.0.1, mq_connect_ip=172.19.2.2 (local), world_size=2, local_world_size=2
(Worker pid=216) INFO 09-06 19:34:03 [parallel_state.py:1638] world_size=2 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_d15710e8eb6f474d97f2f492f33076e8 backend=nccl
(Worker pid=217) INFO 09-06 19:34:03 [parallel_state.py:1638] world_size=2 rank=1 local_rank=1 distributed_init_method=file:///tmp/vllm_dist_d15710e8eb6f474d97f2f492f33076e8 backend=nccl
(Worker pid=216) INFO 09-06 19:34:07 [pynccl.py:113] vLLM is using nccl==2.29.7
(Worker pid=216) (Worker pid=217) WARNING 09-06 19:34:08 [symm_mem.py:67] SymmMemCommunicator: Device capability 7.5 not supported, communicator is not available.
WARNING 09-06 19:34:08 [symm_mem.py:67] SymmMemCommunicator: Device capability 7.5 not supported, communicator is not available.
(Worker pid=216) INFO 09-06 19:34:08 [cuda_communicator.py:266] Using ['CUSTOM', 'PYNCCL'] all-reduce backends (in dispatch order) for group 'tp:0' out of potential backends: ['NCCL_SYMM_MEM', 'QUICK_REDUCE', 'FLASHINFER', 'AITER_CUSTOM', 'CUSTOM', 'SYMM_MEM', 'PYNCCL'].
(Worker pid=216) INFO 09-06 19:34:08 [parallel_state.py:1982] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(Worker pid=216) INFO 09-06 19:34:08 [gpu_worker.py:396] Using V2 Model Runner
(Worker_TP0 pid=216) INFO 09-06 19:34:09 [model_runner.py:358] Loading model from scratch...
(Worker_TP0 pid=216) ERROR 09-06 19:34:09 [fa_utils.py:200] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
(Worker_TP1 pid=217) ERROR 09-06 19:34:09 [fa_utils.py:200] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
(Worker_TP0 pid=216) INFO 09-06 19:34:09 [cuda.py:486] Using TRITON_ATTN attention backend out of potential backends: ['TRITON_ATTN', 'FLEX_ATTENTION'].

model.safetensors.index.json:   0%|          | 0.00/32.8k [00:00<?, ?B/s]

(Worker_TP0 pid=216) INFO 09-06 19:34:38 [weight_utils.py:521] Time spent downloading weights for Qwen/Qwen3-4B-Instruct-2507: 27.845819 seconds
(Worker_TP0 pid=216) INFO 09-06 19:34:38 [weight_utils.py:858] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 7.49 GiB. Available RAM: 9.23 GiB.
(Worker_TP0 pid=216) INFO 09-06 19:34:38 [weight_utils.py:881] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]

(Worker_TP0 pid=216) INFO 09-06 19:34:42 [default_loader.py:430] Loading weights took 3.95 seconds
(Worker_TP0 pid=216) INFO 09-06 19:34:43 [model_runner.py:380] Model loading took 3.9 GiB memory and 34.279103 seconds
(Worker_TP0 pid=216) WARNING 09-06 19:34:43 [topk_topp_sampler.py:69] FlashInfer top-p/top-k sampling unavailable: unsupported compute capability 7.5; falling back. Set VLLM_USE_FLASHINFER_SAMPLER=0 to silence.
(Worker_TP1 pid=217) INFO 09-06 19:34:44 [model_runner.py:380] Model loading took 3.9 GiB memory and 35.624807 seconds
(EngineCore pid=201) INFO 09-06 19:34:44 [torch_utils.py:262] Reducing Torch threads from 2 to 1 for serving. Set OMP_NUM_THREADS in the external environment to override.
(Worker_TP0 pid=216) INFO 09-06 19:35:01 [backends.py:1094] Using cache directory: /root/.cache/vllm/torch_compile_cache/7a41710ae5/rank_0_0/backbone for vLLM's torch.compile
(Worker_TP0 pid=216) INFO 09-06 19:35:01 [backends.py:1155] Dynamo bytecode transform time: 12.23 s

(Worker_TP0 pid=216) [rank0]:W0906 19:35:03.995000 216 torch/_inductor/utils.py:1953] Not enough SMs to use max_autotune_gemm mode
(Worker_TP1 pid=217) [rank1]:W0906 19:35:04.159000 217 torch/_inductor/utils.py:1953] Not enough SMs to use max_autotune_gemm mode

(Worker_TP1 pid=217) INFO 09-06 19:35:28 [backends.py:920] collected artifacts: 37 entries, 3 artifacts, 6008172 bytes total
(Worker_TP0 pid=216) INFO 09-06 19:35:29 [backends.py:393] Compiling a graph for compile range (1, 8192) takes 26.62 s
(Worker_TP0 pid=216) INFO 09-06 19:35:35 [backends.py:920] collected artifacts: 37 entries, 3 artifacts, 5800019 bytes total
(Worker_TP0 pid=216) INFO 09-06 19:35:35 [decorators.py:708] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/763a78e537a2faaddadd6abad7d6ecac5f9aa75e604b1b6fc01265a02fb768ef/rank_0_0/model
(Worker_TP0 pid=216) INFO 09-06 19:35:35 [monitor.py:53] torch.compile took 46.37 s in total
(Worker_TP0 pid=216) INFO 09-06 19:35:35 [monitor.py:81] Initial profiling/warmup run took 0.14 s
(Worker_TP0 pid=216) INFO 09-06 19:35:39 [gpu_worker.py:578] Available KV cache memory: 8.31 GiB
(EngineCore pid=201) INFO 09-06 19:35:39 [kv_cache_utils.py:1869] GPU KV cache size: 121,024 tokens, Maximum concurrency for 1,024 tokens per request: 118.19x

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 51/51 [00:10<00:00,  4.96it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 35/35 [00:02<00:00, 12.35it/s]

(Worker_TP1 pid=217) INFO 09-06 19:35:54 [model_runner.py:906] Graph capturing finished in 14 secs, took 0.55 GiB
(Worker_TP1 pid=217) INFO 09-06 19:35:54 [gpu_worker.py:804] Free memory on device (14.32/14.56 GiB) on startup. Desired GPU memory utilization is (0.9, 13.11 GiB). Actual usage is 4.44 GiB for consumed memory (weights + non-torch), 0.36 GiB for peak activation, and 0.55 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=8172260557` (7.61 GiB) to fit into requested memory, or `--kv-cache-memory=9472802816` (8.82 GiB) to fully utilize gpu memory. Current kv cache memory in use is 8.31 GiB.
(Worker_TP0 pid=216) INFO 09-06 19:35:54 [model_runner.py:906] Graph capturing finished in 14 secs, took 0.54 GiB
(Worker_TP0 pid=216) INFO 09-06 19:35:54 [gpu_worker.py:804] Free memory on device (14.32/14.56 GiB) on startup. Desired GPU memory utilization is (0.9, 13.11 GiB). Actual usage is 4.44 GiB for consumed memory (weights + non-torch), 0.36 GiB for peak activation, and 0.54 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=8184843469` (7.62 GiB) to fit into requested memory, or `--kv-cache-memory=9485385728` (8.83 GiB) to fully utilize gpu memory. Current kv cache memory in use is 8.31 GiB.
(Worker_TP0 pid=216) INFO 09-06 19:36:03 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.
(Worker_TP1 pid=217) INFO 09-06 19:36:03 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.
(Worker_TP0 pid=216) INFO 09-06 19:36:04 [torch_utils.py:262] Reducing Torch threads from 2 to 1 for serving. Set OMP_NUM_THREADS in the external environment to override.
(EngineCore pid=201) INFO 09-06 19:36:04 [core.py:347] init engine (profile, create kv cache, warmup model) took 79.73 s (compilation: 46.37 s)
(EngineCore pid=201) INFO 09-06 19:36:05 [kernel.py:308] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-06 19:36:07 [hf.py:551] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

In [3]:
import itertools
import json
import random

# 1. Define Taxonomy
tech_labels = [
    "Artificial Intelligence",
    "Cloud Computing",
    "Cybersecurity",
    "Quantum Computing",
    "Data Science",
    "Telecommunications",
    "Software Engineering",
    "Autonomous Vehicles",
    "Space Technology",
    "Robotics",
    "Internet of Things (IoT)",
    "Financial Technology (FinTech)",
    "Augmented & Virtual Reality (AR/VR)",
    "Cryptography",
]
science_labels = [
    "Genomics",
    "Astrophysics",
    "Materials Science",
    "Neuroscience",
    "Physics",
    "Astrophysics",
    "Particle Physics",
    "Quantum Physics",
    "Nuclear Physics",
    "Chemistry",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Mathematics",
    "Statistics",
    "Applied Mathematics",
    "Aerospace",
    "Climate Science",
    "Energy Science",
]

# all_labels = tech_labels + science_labels

formats = [
    "Research Paper Abstract",
    "Tech Blog Post",
    "Industry News Brief",
    "Patent Application Summary",
    "Scientific News Article",
    "Technical Report",
    "Product Announcement",
    "Company Press Release",
    "Policy Brief",
    "Case Study",
    "Research Finding Report",
    "Technology Trend Report",
    "Science Explainer",
    "Technical Documentation",
    "Market Research Summary",
]
styles = [
    "Formal",
    "Technical",
    "Journalistic",
    "Academic",
    "Analytical",
    "Descriptive",
    "Concise",
    "Explanatory",
    "Business-oriented",
    "Critical",
]

lengths = ["Short (50-100 words)", "Medium (100-200 words)", "Long (200-350 words)"]

In [4]:
prompt_template = """SYSTEM PROMPT:
You are an expert dataset generator specializing in creating high-quality, realistic synthetic text for machine learning models.

TASK:
Generate a single synthetic dataset item for a multi-label text classification model operating across the TECHNOLOGY and SCIENCE domains.

TARGET LABELS TO IMPLY:
- Selected Labels: {TARGET_LABELS}

STYLISTIC & DOMAIN CONSTRAINTS:
- Format / Genre: {TEXT_FORMAT} (e.g., peer-reviewed abstract excerpt, tech blog entry, research forum post, product announcement, patent abstract)
- Tone / Audience: {TONE_STYLE} (e.g., highly academic, practitioner-focused, journalistic, speculative)
- Length: {LENGTH_RANGE} words.
- Opening Sentence Style: {OPENING_STYLE}

GENERATION RULES:
1. Multi-Label Grounding: The generated text MUST genuinely embody ALL the topics listed in {TARGET_LABELS}. The topics must be naturally interwoven rather than forced.
2. Avoid Explicit Label Speller ("Label Leakage"): DO NOT simply repeat the exact name of the target labels in the text unless necessary. Express the underlying concepts, methodologies, and terminology instead.
3. Sentence Starter Variety: Strictly adhere to the requested Opening Sentence Style. NEVER start the text with repetitive filler openers like "A new...", "A recent...", "The project...", or "In this paper...".
4. Realistic Noise & Edge Cases: Make the text sound authentic to its format. Include relevant domain jargon, technical acronyms, or real-world contextual nuances.
5. Output Format: Return STRICTLY a valid JSON object. Do not include markdown code block syntax (e.g., ```json) or any explanatory text before or after the JSON.

EXPECTED JSON SCHEMA:
{{
  "text": "The generated synthetic paragraph...",
  "labels": ["Label1", "Label2"],
  "difficulty_level": "beginner | intermediate | advanced"
}}"""

In [5]:
# formatted_prompt

In [6]:
import re
opening_styles = [
    # Direct Action & Imperatives
    "Start with a direct action or gerund verb (e.g., 'Deploying...', 'Optimizing...')",
    "Start with an imperative instruction (e.g., 'Configure the cluster...', 'Ensure that...')",
    
    # Scenarios & Problem Framing
    "Start with a problem statement or scenario (e.g., 'When handling high traffic...')",
    "Start with a pain point or anti-pattern (e.g., 'A common mistake in microservices is...')",
    "Start with a hypothetical condition (e.g., 'If your primary database fails...')",
    
    # Direct Technical Naming & Definitions
    "Start with a technical concept or tool name directly (e.g., 'Kubernetes handles...', 'Redis caching...')",
    "Start with a crisp technical definition (e.g., 'Idempotency ensures that...')",
    
    # Time, Preconditions & Sequence
    "Start with a temporal or conditional phrase (e.g., 'Before configuring...', 'Prior to release...')",
    "Start with a step in a sequence (e.g., 'First, establish a baseline...')",
    
    # Industry Context & Comparisons
    "Start with a contrast or trade-off (e.g., 'Unlike relational databases, key-value stores...')",
    "Start with an industry standard or best practice (e.g., 'Modern CI/CD pipelines require...')",
    
    # Analytical & Question-Driven
    "Start with a technical question (e.g., 'Why do distributed systems require...')",
    "Start with a quantitative or metric-focused observation (e.g., 'Reducing latency by 20% requires...')"
]

def generate_prompt_payload():
    # Pick 2 to 3 random overlapping labels to enforce multi-label coverage
    k = random.choice([1,2,3,4,5,6])
    selected_labels = random.sample(tech_labels, k)

    fmt = random.choice(formats)
    tone = random.choice(styles)

    # Return parameters to format into the system prompt template above
    return {
        "TARGET_LABELS": selected_labels,
        "TEXT_FORMAT": fmt,
        "TONE_STYLE": tone,
        "LENGTH_RANGE": random.choice(lengths),
        "OPENING_STYLE": random.choice(opening_styles),
    }

def extract_json_payload(text: str):
    """Extracts JSON content using regular expressions to handle leading/trailing text."""
    # Search for content inside ```json ... ``` or standard ``` ... ```
    match = re.search(r"```(?:json)?\s*(\{.*\}|\[.*\])\s*```", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    
    # Fallback search for bare structural JSON bounds
    match = re.search(r"(\{.*\}|\[.*\])", text, re.DOTALL)
    if match:
        return match.group(1).strip()
        
    return text.strip()
    
# 2. Batch Construction
NUM_SAMPLES = 20000  # Adjust as needed
BATCH_SIZE = 100
sampling_params = SamplingParams(
    temperature=0.8,
    top_p = 0.9,
    max_tokens=1024,
    stop=["<|im_end|>", "<|endoftext|>"]
)


dataset = []
failed_count = 0

for i in range(0, NUM_SAMPLES, BATCH_SIZE):
    chunk_size = min(BATCH_SIZE, NUM_SAMPLES - i)
    print(f"Processing batch {i // BATCH_SIZE + 1}/{(NUM_SAMPLES + BATCH_SIZE - 1) // BATCH_SIZE} ({chunk_size} items)...")
    
    batch_prompts = []
    batch_metadata = []
    
    for _ in range(chunk_size):
        payload = generate_prompt_payload()
        formatted_prompt = prompt_template.format(**payload)
        chat_prompt = f"<|im_start|>system\nYou are a helpful assistant. Output valid JSON only.<|im_end|>\n<|im_start|>user\n{formatted_prompt}<|im_end|>\n<|im_start|>assistant\n"
        
        batch_prompts.append(chat_prompt)
        batch_metadata.append(payload)
        
    outputs = llm.generate(batch_prompts, sampling_params, use_tqdm=True)
    
    for output, meta in zip(outputs, batch_metadata):
        raw_text = output.outputs[0].text
        cleaned_json_str = extract_json_payload(raw_text)

        try:
            parsed_json = json.loads(cleaned_json_str)
            dataset.append({
                "text": parsed_json.get("text", ""),
                "labels": parsed_json.get("labels", []),
                "difficulty_level": parsed_json.get("difficulty_level", "intermediate"),
                "target_labels_requested": meta["TARGET_LABELS"],
                "format": meta["TEXT_FORMAT"],
                "style": meta["TONE_STYLE"]
            })
        except json.JSONDecodeError:
            failed_count += 1
            continue

print(f"Dataset generated with {len(dataset)} valid rows. (Failed parse count: {failed_count})")

Processing batch 1/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  2.00it/s, est. speed input: 908.11 toks/s, output: 421.26 toks/s]

Processing batch 2/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.20it/s, est. speed input: 1003.82 toks/s, output: 432.34 toks/s]

Processing batch 3/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 938.13 toks/s, output: 452.66 toks/s]

Processing batch 4/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 941.71 toks/s, output: 457.21 toks/s]

Processing batch 5/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 974.22 toks/s, output: 439.98 toks/s]

Processing batch 6/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.13it/s, est. speed input: 976.50 toks/s, output: 437.35 toks/s]

Processing batch 7/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 961.85 toks/s, output: 447.68 toks/s]

Processing batch 8/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 950.42 toks/s, output: 450.93 toks/s]

Processing batch 9/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 945.37 toks/s, output: 462.78 toks/s]

Processing batch 10/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 965.82 toks/s, output: 445.66 toks/s]

Processing batch 11/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 957.33 toks/s, output: 449.01 toks/s]

Processing batch 12/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 962.12 toks/s, output: 448.99 toks/s]

Processing batch 13/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 963.47 toks/s, output: 444.33 toks/s]

Processing batch 14/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 980.06 toks/s, output: 447.49 toks/s]

Processing batch 15/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 919.76 toks/s, output: 456.98 toks/s]

Processing batch 16/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 970.05 toks/s, output: 449.31 toks/s]

Processing batch 17/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 947.68 toks/s, output: 454.03 toks/s]

Processing batch 18/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 940.63 toks/s, output: 456.42 toks/s]

Processing batch 19/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 956.63 toks/s, output: 447.45 toks/s]

Processing batch 20/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.15it/s, est. speed input: 977.46 toks/s, output: 447.13 toks/s]

Processing batch 21/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 959.56 toks/s, output: 449.58 toks/s]

Processing batch 22/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 958.34 toks/s, output: 450.76 toks/s]

Processing batch 23/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 981.76 toks/s, output: 440.20 toks/s]

Processing batch 24/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 970.72 toks/s, output: 447.49 toks/s]

Processing batch 25/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.21it/s, est. speed input: 1003.72 toks/s, output: 441.17 toks/s]

Processing batch 26/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 975.73 toks/s, output: 447.46 toks/s]

Processing batch 27/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.22it/s, est. speed input: 1011.17 toks/s, output: 436.18 toks/s]

Processing batch 28/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 957.47 toks/s, output: 448.82 toks/s]

Processing batch 29/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 947.90 toks/s, output: 458.02 toks/s]

Processing batch 30/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.15it/s, est. speed input: 980.34 toks/s, output: 445.23 toks/s]

Processing batch 31/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 936.17 toks/s, output: 454.97 toks/s]

Processing batch 32/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 939.75 toks/s, output: 454.92 toks/s]

Processing batch 33/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.21it/s, est. speed input: 1006.73 toks/s, output: 434.62 toks/s]

Processing batch 34/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 965.24 toks/s, output: 448.47 toks/s]

Processing batch 35/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 923.29 toks/s, output: 455.39 toks/s]

Processing batch 36/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 956.23 toks/s, output: 457.55 toks/s]

Processing batch 37/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 959.57 toks/s, output: 446.42 toks/s]

Processing batch 38/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 967.25 toks/s, output: 450.97 toks/s]

Processing batch 39/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 955.82 toks/s, output: 453.95 toks/s]

Processing batch 40/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.08it/s, est. speed input: 955.85 toks/s, output: 453.06 toks/s]

Processing batch 41/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 955.66 toks/s, output: 442.74 toks/s]

Processing batch 42/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.15it/s, est. speed input: 989.01 toks/s, output: 442.59 toks/s]

Processing batch 43/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 949.52 toks/s, output: 456.79 toks/s]

Processing batch 44/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 979.37 toks/s, output: 439.61 toks/s]

Processing batch 45/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.08it/s, est. speed input: 950.68 toks/s, output: 451.87 toks/s]

Processing batch 46/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 961.88 toks/s, output: 446.27 toks/s]

Processing batch 47/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.17it/s, est. speed input: 991.34 toks/s, output: 440.41 toks/s]

Processing batch 48/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 944.19 toks/s, output: 455.79 toks/s]

Processing batch 49/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 958.99 toks/s, output: 454.89 toks/s]

Processing batch 50/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 953.38 toks/s, output: 449.74 toks/s]

Processing batch 51/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 961.16 toks/s, output: 450.30 toks/s]

Processing batch 52/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 951.43 toks/s, output: 455.46 toks/s]

Processing batch 53/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 951.77 toks/s, output: 451.68 toks/s]

Processing batch 54/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.13it/s, est. speed input: 968.45 toks/s, output: 449.13 toks/s]

Processing batch 55/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 936.62 toks/s, output: 450.82 toks/s]

Processing batch 56/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 975.42 toks/s, output: 447.54 toks/s]

Processing batch 57/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.04it/s, est. speed input: 941.71 toks/s, output: 454.25 toks/s]

Processing batch 58/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 949.31 toks/s, output: 444.30 toks/s]

Processing batch 59/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 925.15 toks/s, output: 462.26 toks/s]

Processing batch 60/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.19it/s, est. speed input: 1003.26 toks/s, output: 440.25 toks/s]

Processing batch 61/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 945.70 toks/s, output: 456.39 toks/s]

Processing batch 62/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 932.94 toks/s, output: 450.78 toks/s]

Processing batch 63/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 940.86 toks/s, output: 456.05 toks/s]

Processing batch 64/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.17it/s, est. speed input: 991.87 toks/s, output: 440.18 toks/s]

Processing batch 65/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 964.04 toks/s, output: 444.75 toks/s]

Processing batch 66/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 965.59 toks/s, output: 447.42 toks/s]

Processing batch 67/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 968.72 toks/s, output: 445.91 toks/s]

Processing batch 68/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 929.04 toks/s, output: 454.72 toks/s]

Processing batch 69/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:44<00:00,  2.23it/s, est. speed input: 1010.65 toks/s, output: 436.87 toks/s]

Processing batch 70/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.08it/s, est. speed input: 949.22 toks/s, output: 459.59 toks/s]

Processing batch 71/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 962.38 toks/s, output: 457.27 toks/s]

Processing batch 72/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.19it/s, est. speed input: 999.80 toks/s, output: 444.36 toks/s]

Processing batch 73/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 956.85 toks/s, output: 446.76 toks/s]

Processing batch 74/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 976.86 toks/s, output: 444.65 toks/s]

Processing batch 75/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 966.71 toks/s, output: 447.40 toks/s]

Processing batch 76/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 960.18 toks/s, output: 443.12 toks/s]

Processing batch 77/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 958.20 toks/s, output: 451.78 toks/s]

Processing batch 78/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 947.99 toks/s, output: 453.74 toks/s]

Processing batch 79/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 903.41 toks/s, output: 463.71 toks/s]

Processing batch 80/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 919.99 toks/s, output: 461.97 toks/s]

Processing batch 81/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 973.63 toks/s, output: 439.89 toks/s]

Processing batch 82/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.13it/s, est. speed input: 970.86 toks/s, output: 445.62 toks/s]

Processing batch 83/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.20it/s, est. speed input: 1006.19 toks/s, output: 447.73 toks/s]

Processing batch 84/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 956.21 toks/s, output: 454.74 toks/s]

Processing batch 85/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 948.77 toks/s, output: 452.23 toks/s]

Processing batch 86/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.15it/s, est. speed input: 981.30 toks/s, output: 442.53 toks/s]

Processing batch 87/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.15it/s, est. speed input: 977.15 toks/s, output: 447.46 toks/s]

Processing batch 88/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 944.03 toks/s, output: 456.51 toks/s]

Processing batch 89/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 951.32 toks/s, output: 438.16 toks/s]

Processing batch 90/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.16it/s, est. speed input: 978.56 toks/s, output: 446.15 toks/s]

Processing batch 91/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.16it/s, est. speed input: 985.38 toks/s, output: 445.70 toks/s]

Processing batch 92/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 974.44 toks/s, output: 443.63 toks/s]

Processing batch 93/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 956.32 toks/s, output: 456.29 toks/s]

Processing batch 94/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 968.96 toks/s, output: 446.76 toks/s]

Processing batch 95/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 943.30 toks/s, output: 450.50 toks/s]

Processing batch 96/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 968.10 toks/s, output: 445.10 toks/s]

Processing batch 97/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 966.58 toks/s, output: 448.12 toks/s]

Processing batch 98/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 954.83 toks/s, output: 452.96 toks/s]

Processing batch 99/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.18it/s, est. speed input: 990.23 toks/s, output: 440.56 toks/s]

Processing batch 100/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 977.44 toks/s, output: 442.42 toks/s]

Processing batch 101/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 905.35 toks/s, output: 466.44 toks/s]

Processing batch 102/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 937.79 toks/s, output: 452.07 toks/s]

Processing batch 103/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 926.03 toks/s, output: 451.35 toks/s]

Processing batch 104/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 956.14 toks/s, output: 447.80 toks/s]

Processing batch 105/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 943.98 toks/s, output: 455.82 toks/s]

Processing batch 106/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 953.66 toks/s, output: 444.72 toks/s]

Processing batch 107/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 937.98 toks/s, output: 458.04 toks/s]

Processing batch 108/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.19it/s, est. speed input: 1005.72 toks/s, output: 440.18 toks/s]

Processing batch 109/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 935.46 toks/s, output: 451.26 toks/s]

Processing batch 110/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 963.66 toks/s, output: 447.46 toks/s]

Processing batch 111/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.18it/s, est. speed input: 989.37 toks/s, output: 437.73 toks/s]

Processing batch 112/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 970.93 toks/s, output: 448.28 toks/s]

Processing batch 113/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 961.09 toks/s, output: 450.11 toks/s]

Processing batch 114/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 926.30 toks/s, output: 452.09 toks/s]

Processing batch 115/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 963.60 toks/s, output: 447.35 toks/s]

Processing batch 116/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 963.05 toks/s, output: 451.75 toks/s]

Processing batch 117/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 946.52 toks/s, output: 455.42 toks/s]

Processing batch 118/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.96it/s, est. speed input: 903.24 toks/s, output: 461.67 toks/s]

Processing batch 119/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.17it/s, est. speed input: 990.61 toks/s, output: 442.81 toks/s]

Processing batch 120/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 940.90 toks/s, output: 451.70 toks/s]

Processing batch 121/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 962.16 toks/s, output: 446.75 toks/s]

Processing batch 122/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 958.86 toks/s, output: 446.29 toks/s]

Processing batch 123/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.16it/s, est. speed input: 973.42 toks/s, output: 450.31 toks/s]

Processing batch 124/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:44<00:00,  2.22it/s, est. speed input: 1014.20 toks/s, output: 440.33 toks/s]

Processing batch 125/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 921.22 toks/s, output: 464.60 toks/s]

Processing batch 126/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 954.47 toks/s, output: 443.09 toks/s]

Processing batch 127/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 954.36 toks/s, output: 456.30 toks/s]

Processing batch 128/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 970.96 toks/s, output: 443.13 toks/s]

Processing batch 129/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 970.29 toks/s, output: 445.70 toks/s]

Processing batch 130/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.21it/s, est. speed input: 1008.72 toks/s, output: 439.50 toks/s]

Processing batch 131/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 975.94 toks/s, output: 448.35 toks/s]

Processing batch 132/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 960.28 toks/s, output: 446.37 toks/s]

Processing batch 133/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.17it/s, est. speed input: 993.41 toks/s, output: 437.17 toks/s]

Processing batch 134/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 955.97 toks/s, output: 446.39 toks/s]

Processing batch 135/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.16it/s, est. speed input: 981.49 toks/s, output: 447.41 toks/s]

Processing batch 136/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 946.55 toks/s, output: 457.66 toks/s]

Processing batch 137/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:44<00:00,  2.25it/s, est. speed input: 1021.08 toks/s, output: 440.79 toks/s]

Processing batch 138/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 975.41 toks/s, output: 451.27 toks/s]

Processing batch 139/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 944.26 toks/s, output: 450.66 toks/s]

Processing batch 140/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 943.47 toks/s, output: 452.29 toks/s]

Processing batch 141/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 960.67 toks/s, output: 453.37 toks/s]

Processing batch 142/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.08it/s, est. speed input: 947.96 toks/s, output: 457.22 toks/s]

Processing batch 143/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 966.56 toks/s, output: 445.57 toks/s]

Processing batch 144/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.16it/s, est. speed input: 987.93 toks/s, output: 440.84 toks/s]

Processing batch 145/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 959.18 toks/s, output: 456.06 toks/s]

Processing batch 146/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 938.17 toks/s, output: 458.44 toks/s]

Processing batch 147/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 965.12 toks/s, output: 449.94 toks/s]

Processing batch 148/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 980.00 toks/s, output: 443.31 toks/s]

Processing batch 149/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.15it/s, est. speed input: 977.43 toks/s, output: 445.39 toks/s]

Processing batch 150/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 946.25 toks/s, output: 455.39 toks/s]

Processing batch 151/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.20it/s, est. speed input: 1000.54 toks/s, output: 442.35 toks/s]

Processing batch 152/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 954.60 toks/s, output: 451.25 toks/s]

Processing batch 153/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 963.64 toks/s, output: 453.95 toks/s]

Processing batch 154/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 964.37 toks/s, output: 437.05 toks/s]

Processing batch 155/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 960.13 toks/s, output: 451.28 toks/s]

Processing batch 156/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 947.87 toks/s, output: 454.89 toks/s]

Processing batch 157/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.16it/s, est. speed input: 990.22 toks/s, output: 430.08 toks/s]

Processing batch 158/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.15it/s, est. speed input: 976.19 toks/s, output: 445.04 toks/s]

Processing batch 159/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 921.13 toks/s, output: 461.10 toks/s]

Processing batch 160/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 955.58 toks/s, output: 451.02 toks/s]

Processing batch 161/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 955.71 toks/s, output: 455.15 toks/s]

Processing batch 162/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.15it/s, est. speed input: 972.07 toks/s, output: 450.59 toks/s]

Processing batch 163/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.08it/s, est. speed input: 951.03 toks/s, output: 451.44 toks/s]

Processing batch 164/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 953.89 toks/s, output: 452.02 toks/s]

Processing batch 165/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 974.44 toks/s, output: 437.45 toks/s]

Processing batch 166/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 958.92 toks/s, output: 450.99 toks/s]

Processing batch 167/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.20it/s, est. speed input: 1002.61 toks/s, output: 443.93 toks/s]

Processing batch 168/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 920.23 toks/s, output: 456.68 toks/s]

Processing batch 169/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.17it/s, est. speed input: 991.19 toks/s, output: 442.98 toks/s]

Processing batch 170/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 978.71 toks/s, output: 444.42 toks/s]

Processing batch 171/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 970.18 toks/s, output: 446.04 toks/s]

Processing batch 172/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 948.32 toks/s, output: 448.24 toks/s]

Processing batch 173/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.17it/s, est. speed input: 987.43 toks/s, output: 434.23 toks/s]

Processing batch 174/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.18it/s, est. speed input: 994.68 toks/s, output: 442.42 toks/s]

Processing batch 175/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 964.91 toks/s, output: 445.77 toks/s]

Processing batch 176/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.17it/s, est. speed input: 986.88 toks/s, output: 442.05 toks/s]

Processing batch 177/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.17it/s, est. speed input: 983.85 toks/s, output: 448.19 toks/s]

Processing batch 178/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.18it/s, est. speed input: 996.61 toks/s, output: 443.63 toks/s]

Processing batch 179/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 945.15 toks/s, output: 455.37 toks/s]

Processing batch 180/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 956.52 toks/s, output: 443.91 toks/s]

Processing batch 181/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 966.55 toks/s, output: 448.24 toks/s]

Processing batch 182/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.13it/s, est. speed input: 966.85 toks/s, output: 449.38 toks/s]

Processing batch 183/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 971.65 toks/s, output: 453.59 toks/s]

Processing batch 184/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.08it/s, est. speed input: 947.25 toks/s, output: 455.00 toks/s]

Processing batch 185/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 976.37 toks/s, output: 446.10 toks/s]

Processing batch 186/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 974.84 toks/s, output: 449.51 toks/s]

Processing batch 187/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.15it/s, est. speed input: 974.20 toks/s, output: 448.16 toks/s]

Processing batch 188/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 946.64 toks/s, output: 447.56 toks/s]

Processing batch 189/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.20it/s, est. speed input: 1000.25 toks/s, output: 445.24 toks/s]

Processing batch 190/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 979.12 toks/s, output: 443.77 toks/s]

Processing batch 191/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.20it/s, est. speed input: 998.42 toks/s, output: 441.78 toks/s]

Processing batch 192/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 922.28 toks/s, output: 462.25 toks/s]

Processing batch 193/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.13it/s, est. speed input: 974.14 toks/s, output: 447.46 toks/s]

Processing batch 194/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.19it/s, est. speed input: 1002.95 toks/s, output: 440.13 toks/s]

Processing batch 195/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.16it/s, est. speed input: 983.80 toks/s, output: 445.61 toks/s]

Processing batch 196/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.08it/s, est. speed input: 951.53 toks/s, output: 453.55 toks/s]

Processing batch 197/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 974.97 toks/s, output: 440.81 toks/s]

Processing batch 198/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 918.21 toks/s, output: 457.96 toks/s]

Processing batch 199/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 933.91 toks/s, output: 457.19 toks/s]

Processing batch 200/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.21it/s, est. speed input: 1005.20 toks/s, output: 433.91 toks/s]

Dataset generated with 20000 valid rows. (Failed parse count: 0)

In [7]:
import pandas as pd
df = pd.DataFrame(dataset)
df['all_labels'] = df.apply(lambda _: tech_labels, axis=1)
df

,text,labels,difficulty_level,target_labels_requested,format,style,all_labels
0,A common mistake in distributed systems develo...,"[Augmented & Virtual Reality (AR/VR), Software...",advanced,"[Augmented & Virtual Reality (AR/VR), Software...",Company Press Release,Academic,"[Artificial Intelligence, Cloud Computing, Cyb..."
1,Modern CI/CD pipelines require robust security...,"[Autonomous Vehicles, Space Technology, Crypto...",advanced,"[Autonomous Vehicles, Space Technology, Crypto...",Research Paper Abstract,Technical,"[Artificial Intelligence, Cloud Computing, Cyb..."
2,Why do distributed systems require robust auth...,"[Cybersecurity, Cryptography]",advanced,"[Cybersecurity, Cryptography]",Research Paper Abstract,Formal,"[Artificial Intelligence, Cloud Computing, Cyb..."
3,Deploying a scalable machine learning pipeline...,"[Data Science, Cloud Computing]",advanced,"[Data Science, Cloud Computing]",Technical Report,Concise,"[Artificial Intelligence, Cloud Computing, Cyb..."
4,"First, establish a baseline for low-latency da...","[Telecommunications, Space Technology, Softwar...",advanced,"[Telecommunications, Space Technology, Softwar...",Science Explainer,Academic,"[Artificial Intelligence, Cloud Computing, Cyb..."
...,...,...,...,...,...,...,...
19995,"Prior to release in late 2024, the StarLink-7 ...","[Augmented & Virtual Reality (AR/VR), Artifici...",advanced,"[Augmented & Virtual Reality (AR/VR), Artifici...",Scientific News Article,Journalistic,"[Artificial Intelligence, Cloud Computing, Cyb..."
19996,"Prior to release in 2024, the development team...",[Autonomous Vehicles],advanced,[Autonomous Vehicles],Technical Documentation,Academic,"[Artificial Intelligence, Cloud Computing, Cyb..."
19997,"First, establish a baseline for autonomous nav...","[Autonomous Vehicles, Space Technology, Financ...",advanced,"[Autonomous Vehicles, Space Technology, Financ...",Case Study,Analytical,"[Artificial Intelligence, Cloud Computing, Cyb..."
19998,Reducing latency by 20% requires optimizing si...,"[Telecommunications, Quantum Computing, Cloud ...",advanced,"[Telecommunications, Quantum Computing, Cloud ...",Scientific News Article,Critical,"[Artificial Intelligence, Cloud Computing, Cyb..."
19999,Configure the distributed neural architecture ...,"[Software Engineering, Autonomous Vehicles, Da...",advanced,"[Software Engineering, Autonomous Vehicles, Da...",Scientific News Article,Explanatory,"[Artificial Intelligence, Cloud Computing, Cyb..."

In [8]:


parquet_filename = "synthetic_multilabel_dataset_tech.parquet"
df.to_parquet(parquet_filename, engine="pyarrow", index=False)

print(f"Successfully generated {len(df)} valid items and saved to {parquet_filename}")

Successfully generated 20000 valid items and saved to synthetic_multilabel_dataset_tech.parquet

In [9]:
science_opening_styles = [
    # 1. Methodology & Experimental Direct Action (Gerunds/Verbs)
    "Start with a direct experimental or analytical action (e.g., 'Sequencing high-throughput genomic data...', 'Synthesizing novel perovskite structures...')",
    "Start with an observational procedure (e.g., 'Measuring spin states across superconducting lattices...', 'Tracking stellar spectra in binary systems...')",
    
    # 2. Hypothesis, Phenomena & Scientific Questions
    "Start with a foundational research question (e.g., 'How do epigenetic modifications govern...', 'What mechanisms stabilize non-equilibrium states in...')",
    "Start with a physical or biological phenomenon directly (e.g., 'Dark matter candidate interactions alter...', 'Synaptic plasticity hinges on...')",
    "Start with a theoretical paradox or open question (e.g., 'Reconciling quantum decoherence with macroscopic transport requires...')",

    # 3. Direct Nomenclature, Constants & System Definitions
    "Start directly with a scientific model, compound, or equation (e.g., 'CRISPR-Cas9 complexes target...', 'Graphene's 2D lattice exhibits...')",
    "Start with a rigorous physical definition or fundamental constant (e.g., 'The Pauli exclusion principle dictates that...', 'Enthalpy changes during...')",
    "Start with an organism, material class, or particle (e.g., 'Neutrinos passing through dense interstellar medium...', 'Topological insulators exhibit...')",

    # 4. Quantitative Metrics, Observations & Empirical Data
    "Start with a quantitative measurement or empirical ratio (e.g., 'A 3.2 Kelvin temperature anomaly indicates...', 'Achieving 98% isotopic purity requires...')",
    "Start with a statistical or mathematical observation (e.g., 'Non-linear differential models demonstrate...', 'Monte Carlo simulations reveal...')",

    # 5. Comparative, Contrastive & Paradigm Shifts
    "Start with a contrast between existing models or paradigms (e.g., 'Unlike classical Newtonian fluid dynamics, quantum fluids...', 'Where conventional catalysis fails, metalloenzymes...')",
    "Start with a limitation in current scientific consensus (e.g., 'Standard cosmological models fail to account for...', 'Traditional X-ray crystallography cannot resolve...')",

    # 6. Environmental, Temporal & Pre-experimental Conditions
    "Start with an environmental or lab control condition (e.g., 'Under cryogenic pressures exceeding 200 GPa...', 'Prior to PCR amplification...')",
    "Start with a temporal or geological timeframe (e.g., 'During the early epoch of galaxy formation...', 'Following rapid photo-excitation...')"
]


def generate_prompt_payload():
    k = random.choice([1,2,3,4,5,6])
    selected_labels = random.sample(science_labels, k)

    fmt = random.choice(formats)
    tone = random.choice(styles)
    return {
        "TARGET_LABELS": selected_labels,
        "TEXT_FORMAT": fmt,
        "TONE_STYLE": tone,
        "LENGTH_RANGE": random.choice(lengths),
        "OPENING_STYLE": random.choice(science_opening_styles),
    }
    

NUM_SAMPLES = 20000  # Adjust as needed
BATCH_SIZE = 100
sampling_params = SamplingParams(
    temperature=0.8,
    top_p = 0.9,
    max_tokens=1024,
    stop=["<|im_end|>", "<|endoftext|>"]
)


dataset = []
failed_count = 0

for i in range(0, NUM_SAMPLES, BATCH_SIZE):
    chunk_size = min(BATCH_SIZE, NUM_SAMPLES - i)
    print(f"Processing batch {i // BATCH_SIZE + 1}/{(NUM_SAMPLES + BATCH_SIZE - 1) // BATCH_SIZE} ({chunk_size} items)...")
    
    batch_prompts = []
    batch_metadata = []
    
    for _ in range(chunk_size):
        payload = generate_prompt_payload()
        formatted_prompt = prompt_template.format(**payload)
        chat_prompt = f"<|im_start|>system\nYou are a helpful assistant. Output valid JSON only.<|im_end|>\n<|im_start|>user\n{formatted_prompt}<|im_end|>\n<|im_start|>assistant\n"
        
        batch_prompts.append(chat_prompt)
        batch_metadata.append(payload)
        
    outputs = llm.generate(batch_prompts, sampling_params, use_tqdm=True)
    
    for output, meta in zip(outputs, batch_metadata):
        raw_text = output.outputs[0].text
        cleaned_json_str = extract_json_payload(raw_text)

        try:
            parsed_json = json.loads(cleaned_json_str)
            dataset.append({
                "text": parsed_json.get("text", ""),
                "labels": parsed_json.get("labels", []),
                "difficulty_level": parsed_json.get("difficulty_level", "intermediate"),
                "target_labels_requested": meta["TARGET_LABELS"],
                "format": meta["TEXT_FORMAT"],
                "style": meta["TONE_STYLE"]
            })
        except json.JSONDecodeError:
            failed_count += 1
            continue

print(f"Dataset generated with {len(dataset)} valid rows. (Failed parse count: {failed_count})")

Processing batch 1/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 921.28 toks/s, output: 448.10 toks/s]

Processing batch 2/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 936.39 toks/s, output: 451.93 toks/s]

Processing batch 3/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 957.40 toks/s, output: 437.53 toks/s]

Processing batch 4/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.04it/s, est. speed input: 944.54 toks/s, output: 441.40 toks/s]

Processing batch 5/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 946.26 toks/s, output: 448.17 toks/s]

Processing batch 6/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.98it/s, est. speed input: 919.90 toks/s, output: 450.91 toks/s]

Processing batch 7/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 937.54 toks/s, output: 440.81 toks/s]

Processing batch 8/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 915.93 toks/s, output: 451.05 toks/s]

Processing batch 9/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.04it/s, est. speed input: 941.84 toks/s, output: 443.64 toks/s]

Processing batch 10/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 928.24 toks/s, output: 445.59 toks/s]

Processing batch 11/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  2.00it/s, est. speed input: 920.54 toks/s, output: 451.21 toks/s]

Processing batch 12/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  2.00it/s, est. speed input: 916.71 toks/s, output: 449.73 toks/s]

Processing batch 13/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 895.33 toks/s, output: 452.48 toks/s]

Processing batch 14/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 931.03 toks/s, output: 432.37 toks/s]

Processing batch 15/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 930.71 toks/s, output: 452.93 toks/s]

Processing batch 16/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 977.93 toks/s, output: 452.55 toks/s]

Processing batch 17/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 964.19 toks/s, output: 443.58 toks/s]

Processing batch 18/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 935.01 toks/s, output: 458.02 toks/s]

Processing batch 19/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 914.99 toks/s, output: 447.29 toks/s]

Processing batch 20/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 909.71 toks/s, output: 454.96 toks/s]

Processing batch 21/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 950.67 toks/s, output: 450.02 toks/s]

Processing batch 22/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 906.44 toks/s, output: 454.19 toks/s]

Processing batch 23/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 939.77 toks/s, output: 449.33 toks/s]

Processing batch 24/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 933.74 toks/s, output: 440.62 toks/s]

Processing batch 25/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 899.51 toks/s, output: 453.94 toks/s]

Processing batch 26/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 920.58 toks/s, output: 454.13 toks/s]

Processing batch 27/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.93it/s, est. speed input: 888.15 toks/s, output: 457.35 toks/s]

Processing batch 28/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 945.61 toks/s, output: 445.87 toks/s]

Processing batch 29/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 907.81 toks/s, output: 462.30 toks/s]

Processing batch 30/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.96it/s, est. speed input: 903.38 toks/s, output: 456.11 toks/s]

Processing batch 31/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 901.21 toks/s, output: 453.34 toks/s]

Processing batch 32/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 963.00 toks/s, output: 444.82 toks/s]

Processing batch 33/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.96it/s, est. speed input: 902.23 toks/s, output: 455.57 toks/s]

Processing batch 34/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 941.74 toks/s, output: 448.00 toks/s]

Processing batch 35/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 899.86 toks/s, output: 450.19 toks/s]

Processing batch 36/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 895.73 toks/s, output: 456.40 toks/s]

Processing batch 37/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 969.18 toks/s, output: 444.68 toks/s]

Processing batch 38/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 971.39 toks/s, output: 435.62 toks/s]

Processing batch 39/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 919.03 toks/s, output: 448.46 toks/s]

Processing batch 40/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 902.11 toks/s, output: 456.09 toks/s]

Processing batch 41/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 964.23 toks/s, output: 445.56 toks/s]

Processing batch 42/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.96it/s, est. speed input: 900.35 toks/s, output: 459.07 toks/s]

Processing batch 43/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 910.67 toks/s, output: 450.92 toks/s]

Processing batch 44/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 948.88 toks/s, output: 434.89 toks/s]

Processing batch 45/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.94it/s, est. speed input: 898.79 toks/s, output: 454.07 toks/s]

Processing batch 46/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 938.16 toks/s, output: 448.08 toks/s]

Processing batch 47/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 920.43 toks/s, output: 438.78 toks/s]

Processing batch 48/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 932.13 toks/s, output: 442.55 toks/s]

Processing batch 49/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 966.51 toks/s, output: 440.81 toks/s]

Processing batch 50/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 938.23 toks/s, output: 440.90 toks/s]

Processing batch 51/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.98it/s, est. speed input: 916.61 toks/s, output: 447.94 toks/s]

Processing batch 52/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 923.34 toks/s, output: 445.38 toks/s]

Processing batch 53/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.98it/s, est. speed input: 913.47 toks/s, output: 450.80 toks/s]

Processing batch 54/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:52<00:00,  1.92it/s, est. speed input: 884.60 toks/s, output: 457.46 toks/s]

Processing batch 55/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 908.21 toks/s, output: 448.26 toks/s]

Processing batch 56/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.08it/s, est. speed input: 957.19 toks/s, output: 448.85 toks/s]

Processing batch 57/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 928.60 toks/s, output: 447.48 toks/s]

Processing batch 58/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 911.65 toks/s, output: 449.70 toks/s]

Processing batch 59/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 932.98 toks/s, output: 442.84 toks/s]

Processing batch 60/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 950.07 toks/s, output: 438.58 toks/s]

Processing batch 61/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 917.75 toks/s, output: 450.34 toks/s]

Processing batch 62/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 901.63 toks/s, output: 437.84 toks/s]

Processing batch 63/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.96it/s, est. speed input: 903.75 toks/s, output: 446.76 toks/s]

Processing batch 64/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 928.50 toks/s, output: 456.10 toks/s]

Processing batch 65/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 945.07 toks/s, output: 442.41 toks/s]

Processing batch 66/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 897.17 toks/s, output: 451.06 toks/s]

Processing batch 67/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 929.83 toks/s, output: 449.69 toks/s]

Processing batch 68/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 954.94 toks/s, output: 439.03 toks/s]

Processing batch 69/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 931.68 toks/s, output: 445.26 toks/s]

Processing batch 70/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 965.99 toks/s, output: 445.57 toks/s]

Processing batch 71/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.10it/s, est. speed input: 967.73 toks/s, output: 440.87 toks/s]

Processing batch 72/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 960.69 toks/s, output: 443.79 toks/s]

Processing batch 73/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 945.99 toks/s, output: 452.51 toks/s]

Processing batch 74/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  2.00it/s, est. speed input: 917.61 toks/s, output: 445.96 toks/s]

Processing batch 75/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.94it/s, est. speed input: 893.68 toks/s, output: 442.04 toks/s]

Processing batch 76/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 938.25 toks/s, output: 439.63 toks/s]

Processing batch 77/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.98it/s, est. speed input: 912.55 toks/s, output: 441.21 toks/s]

Processing batch 78/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.98it/s, est. speed input: 912.13 toks/s, output: 452.90 toks/s]

Processing batch 79/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 951.24 toks/s, output: 439.97 toks/s]

Processing batch 80/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 942.69 toks/s, output: 444.19 toks/s]

Processing batch 81/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 933.51 toks/s, output: 450.04 toks/s]

Processing batch 82/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 953.05 toks/s, output: 447.79 toks/s]

Processing batch 83/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.94it/s, est. speed input: 894.01 toks/s, output: 450.95 toks/s]

Processing batch 84/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  2.00it/s, est. speed input: 919.87 toks/s, output: 450.06 toks/s]

Processing batch 85/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 921.58 toks/s, output: 460.52 toks/s]

Processing batch 86/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 943.94 toks/s, output: 439.80 toks/s]

Processing batch 87/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 919.40 toks/s, output: 456.26 toks/s]

Processing batch 88/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 946.06 toks/s, output: 450.42 toks/s]

Processing batch 89/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 909.06 toks/s, output: 457.74 toks/s]

Processing batch 90/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 925.14 toks/s, output: 446.33 toks/s]

Processing batch 91/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.96it/s, est. speed input: 905.75 toks/s, output: 456.97 toks/s]

Processing batch 92/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 931.33 toks/s, output: 450.59 toks/s]

Processing batch 93/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 922.46 toks/s, output: 445.63 toks/s]

Processing batch 94/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  2.00it/s, est. speed input: 923.87 toks/s, output: 444.59 toks/s]

Processing batch 95/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 955.70 toks/s, output: 444.84 toks/s]

Processing batch 96/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 960.24 toks/s, output: 444.95 toks/s]

Processing batch 97/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 926.65 toks/s, output: 435.93 toks/s]

Processing batch 98/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.96it/s, est. speed input: 900.82 toks/s, output: 456.04 toks/s]

Processing batch 99/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 944.36 toks/s, output: 439.24 toks/s]

Processing batch 100/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.96it/s, est. speed input: 900.15 toks/s, output: 449.29 toks/s]

Processing batch 101/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 940.02 toks/s, output: 450.55 toks/s]

Processing batch 102/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:45<00:00,  2.18it/s, est. speed input: 1002.39 toks/s, output: 440.08 toks/s]

Processing batch 103/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 958.41 toks/s, output: 439.31 toks/s]

Processing batch 104/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 972.81 toks/s, output: 441.00 toks/s]

Processing batch 105/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 956.03 toks/s, output: 448.20 toks/s]

Processing batch 106/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 926.52 toks/s, output: 453.16 toks/s]

Processing batch 107/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 962.45 toks/s, output: 446.33 toks/s]

Processing batch 108/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 927.84 toks/s, output: 443.31 toks/s]

Processing batch 109/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 948.36 toks/s, output: 443.78 toks/s]

Processing batch 110/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 962.10 toks/s, output: 439.60 toks/s]

Processing batch 111/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 919.39 toks/s, output: 451.95 toks/s]

Processing batch 112/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 970.69 toks/s, output: 434.74 toks/s]

Processing batch 113/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 950.06 toks/s, output: 449.64 toks/s]

Processing batch 114/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 944.40 toks/s, output: 454.99 toks/s]

Processing batch 115/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 924.34 toks/s, output: 448.73 toks/s]

Processing batch 116/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 959.83 toks/s, output: 439.46 toks/s]

Processing batch 117/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 937.59 toks/s, output: 445.76 toks/s]

Processing batch 118/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 944.87 toks/s, output: 444.88 toks/s]

Processing batch 119/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 954.64 toks/s, output: 438.19 toks/s]

Processing batch 120/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 905.24 toks/s, output: 454.24 toks/s]

Processing batch 121/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 913.71 toks/s, output: 455.15 toks/s]

Processing batch 122/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.98it/s, est. speed input: 914.55 toks/s, output: 446.43 toks/s]

Processing batch 123/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 907.26 toks/s, output: 456.35 toks/s]

Processing batch 124/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 932.92 toks/s, output: 447.83 toks/s]

Processing batch 125/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 929.32 toks/s, output: 456.83 toks/s]

Processing batch 126/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 948.80 toks/s, output: 446.50 toks/s]

Processing batch 127/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 948.53 toks/s, output: 448.92 toks/s]

Processing batch 128/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 913.79 toks/s, output: 460.47 toks/s]

Processing batch 129/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 959.37 toks/s, output: 446.85 toks/s]

Processing batch 130/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 922.73 toks/s, output: 444.41 toks/s]

Processing batch 131/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 944.13 toks/s, output: 440.54 toks/s]

Processing batch 132/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.04it/s, est. speed input: 934.05 toks/s, output: 445.05 toks/s]

Processing batch 133/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 976.68 toks/s, output: 439.02 toks/s]

Processing batch 134/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 928.83 toks/s, output: 458.09 toks/s]

Processing batch 135/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 908.63 toks/s, output: 450.29 toks/s]

Processing batch 136/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 915.92 toks/s, output: 448.15 toks/s]

Processing batch 137/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 946.62 toks/s, output: 445.28 toks/s]

Processing batch 138/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 932.61 toks/s, output: 451.13 toks/s]

Processing batch 139/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 945.66 toks/s, output: 439.57 toks/s]

Processing batch 140/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 950.47 toks/s, output: 438.56 toks/s]

Processing batch 141/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 952.35 toks/s, output: 445.72 toks/s]

Processing batch 142/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 934.33 toks/s, output: 445.56 toks/s]

Processing batch 143/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.96it/s, est. speed input: 903.67 toks/s, output: 446.73 toks/s]

Processing batch 144/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 900.78 toks/s, output: 457.10 toks/s]

Processing batch 145/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 932.44 toks/s, output: 446.01 toks/s]

Processing batch 146/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.11it/s, est. speed input: 972.54 toks/s, output: 434.75 toks/s]

Processing batch 147/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 929.31 toks/s, output: 443.18 toks/s]

Processing batch 148/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 951.05 toks/s, output: 448.38 toks/s]

Processing batch 149/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  2.00it/s, est. speed input: 921.99 toks/s, output: 449.94 toks/s]

Processing batch 150/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 946.28 toks/s, output: 440.62 toks/s]

Processing batch 151/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 899.17 toks/s, output: 463.51 toks/s]

Processing batch 152/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 945.44 toks/s, output: 441.67 toks/s]

Processing batch 153/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  2.00it/s, est. speed input: 918.84 toks/s, output: 448.60 toks/s]

Processing batch 154/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 945.61 toks/s, output: 448.50 toks/s]

Processing batch 155/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:52<00:00,  1.91it/s, est. speed input: 882.40 toks/s, output: 458.82 toks/s]

Processing batch 156/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 937.80 toks/s, output: 448.38 toks/s]

Processing batch 157/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 900.50 toks/s, output: 458.85 toks/s]

Processing batch 158/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.98it/s, est. speed input: 913.79 toks/s, output: 443.26 toks/s]

Processing batch 159/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.93it/s, est. speed input: 895.08 toks/s, output: 454.50 toks/s]

Processing batch 160/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 919.21 toks/s, output: 450.87 toks/s]

Processing batch 161/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  2.00it/s, est. speed input: 925.23 toks/s, output: 443.84 toks/s]

Processing batch 162/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.04it/s, est. speed input: 941.57 toks/s, output: 443.64 toks/s]

Processing batch 163/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 938.89 toks/s, output: 449.13 toks/s]

Processing batch 164/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.03it/s, est. speed input: 938.40 toks/s, output: 440.78 toks/s]

Processing batch 165/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.00it/s, est. speed input: 919.34 toks/s, output: 454.05 toks/s]

Processing batch 166/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 929.35 toks/s, output: 448.75 toks/s]

Processing batch 167/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 950.41 toks/s, output: 442.02 toks/s]

Processing batch 168/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.96it/s, est. speed input: 901.47 toks/s, output: 452.48 toks/s]

Processing batch 169/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 948.51 toks/s, output: 440.91 toks/s]

Processing batch 170/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.05it/s, est. speed input: 939.04 toks/s, output: 446.38 toks/s]

Processing batch 171/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 926.55 toks/s, output: 445.81 toks/s]

Processing batch 172/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 948.97 toks/s, output: 437.72 toks/s]

Processing batch 173/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.94it/s, est. speed input: 895.28 toks/s, output: 455.91 toks/s]

Processing batch 174/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 926.60 toks/s, output: 441.54 toks/s]

Processing batch 175/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 906.70 toks/s, output: 456.48 toks/s]

Processing batch 176/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 899.52 toks/s, output: 454.41 toks/s]

Processing batch 177/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 908.95 toks/s, output: 439.94 toks/s]

Processing batch 178/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 925.70 toks/s, output: 450.01 toks/s]

Processing batch 179/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 916.42 toks/s, output: 457.56 toks/s]

Processing batch 180/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 915.85 toks/s, output: 461.39 toks/s]

Processing batch 181/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.93it/s, est. speed input: 891.13 toks/s, output: 442.78 toks/s]

Processing batch 182/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.97it/s, est. speed input: 912.29 toks/s, output: 457.55 toks/s]

Processing batch 183/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:51<00:00,  1.95it/s, est. speed input: 904.00 toks/s, output: 454.42 toks/s]

Processing batch 184/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 936.54 toks/s, output: 447.24 toks/s]

Processing batch 185/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.04it/s, est. speed input: 936.23 toks/s, output: 448.76 toks/s]

Processing batch 186/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 944.45 toks/s, output: 447.65 toks/s]

Processing batch 187/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 977.81 toks/s, output: 439.28 toks/s]

Processing batch 188/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 933.29 toks/s, output: 454.93 toks/s]

Processing batch 189/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 927.51 toks/s, output: 450.73 toks/s]

Processing batch 190/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:46<00:00,  2.14it/s, est. speed input: 982.29 toks/s, output: 439.22 toks/s]

Processing batch 191/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.02it/s, est. speed input: 931.28 toks/s, output: 444.65 toks/s]

Processing batch 192/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.07it/s, est. speed input: 951.55 toks/s, output: 448.70 toks/s]

Processing batch 193/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:49<00:00,  2.01it/s, est. speed input: 930.49 toks/s, output: 442.75 toks/s]

Processing batch 194/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s, est. speed input: 913.40 toks/s, output: 450.15 toks/s]

Processing batch 195/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.06it/s, est. speed input: 945.31 toks/s, output: 450.87 toks/s]

Processing batch 196/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.12it/s, est. speed input: 979.42 toks/s, output: 433.10 toks/s]

Processing batch 197/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 959.29 toks/s, output: 446.56 toks/s]

Processing batch 198/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 962.21 toks/s, output: 449.39 toks/s]

Processing batch 199/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:47<00:00,  2.09it/s, est. speed input: 960.30 toks/s, output: 446.57 toks/s]

Processing batch 200/200 (100 items)...

Rendering prompts:   0%|          | 0/100 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 100/100 [00:48<00:00,  2.08it/s, est. speed input: 950.07 toks/s, output: 450.43 toks/s]

Dataset generated with 19922 valid rows. (Failed parse count: 78)

In [10]:
import pandas as pd
df = pd.DataFrame(dataset)
df['all_labels'] = df.apply(lambda _: science_labels, axis=1)
df

,text,labels,difficulty_level,target_labels_requested,format,style,all_labels
0,Conducting in-situ X-ray diffraction analysis ...,"[Physical Chemistry, Materials Science, Statis...",advanced,"[Physical Chemistry, Materials Science, Statis...",Technical Documentation,Journalistic,"[Genomics, Astrophysics, Materials Science, Ne..."
1,Neutrinos passing through dense interstellar m...,"[Astrophysics, Nuclear Physics, Neuroscience, ...",advanced,"[Astrophysics, Nuclear Physics, Neuroscience, ...",Research Finding Report,Technical,"[Genomics, Astrophysics, Materials Science, Ne..."
2,Standard thermodynamic models fail to account ...,"[Statistics, Inorganic Chemistry]",advanced,"[Statistics, Inorganic Chemistry]",Product Announcement,Explanatory,"[Genomics, Astrophysics, Materials Science, Ne..."
3,A 97.3% correlation between atmospheric CO2 co...,"[Climate Science, Astrophysics, Organic Chemis...",advanced,"[Climate Science, Astrophysics, Organic Chemis...",Tech Blog Post,Descriptive,"[Genomics, Astrophysics, Materials Science, Ne..."
4,Monitoring quantum entanglement decay in photo...,[Physics],advanced,[Physics],Industry News Brief,Technical,"[Genomics, Astrophysics, Materials Science, Ne..."
...,...,...,...,...,...,...,...
19917,Unlike conventional enzymatic pathways that re...,"[Genomics, Inorganic Chemistry]",advanced,"[Genomics, Inorganic Chemistry]",Tech Blog Post,Descriptive,"[Genomics, Astrophysics, Materials Science, Ne..."
19918,Monte Carlo simulations reveal that regional t...,"[Applied Mathematics, Climate Science]",advanced,"[Applied Mathematics, Climate Science]",Company Press Release,Critical,"[Genomics, Astrophysics, Materials Science, Ne..."
19919,How do thermodynamic fluctuations in quantum f...,"[Physical Chemistry, Statistics]",advanced,"[Physical Chemistry, Statistics]",Research Paper Abstract,Journalistic,"[Genomics, Astrophysics, Materials Science, Ne..."
19920,Reconciling quantum decoherence with macroscop...,"[Neuroscience, Physics, Physical Chemistry, Ge...",advanced,"[Neuroscience, Physics, Physical Chemistry, Ge...",Market Research Summary,Critical,"[Genomics, Astrophysics, Materials Science, Ne..."
19921,Reconciling quantum decoherence with macroscop...,"[Physical Chemistry, Energy Science, Organic C...",advanced,"[Physical Chemistry, Energy Science, Organic C...",Technical Report,Technical,"[Genomics, Astrophysics, Materials Science, Ne..."

In [11]:


parquet_filename = "synthetic_multilabel_dataset_science.parquet"
df.to_parquet(parquet_filename, engine="pyarrow", index=False)

print(f"Successfully generated {len(df)} valid items and saved to {parquet_filename}")

Successfully generated 19922 valid items and saved to synthetic_multilabel_dataset_science.parquet